language: C
sudo: false
compiler:
  - gcc
  - clang
script:
  - make
  - make tests
addons:
  homebrew:
    packages:
      - lua
  apt:
    packages:
      - liblua5.2-dev
  homebrew:
    packages:
      - lua
      - luarocks
os:
  - linux
  - osx
